---
ApplicationProfileName: DragenSomaticIdt
ApplicationProfileVersion: 1.0.0
ApplicationType: Dragen
ApplicationName: DragenSomatic

Settings:
  SoftwareVersion: 4.1.23
  AppVersion: 1.2.1
  MapAlignOutFormat: bam
  KeepFastq: true

Data:
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers
  AuxNoiseBaselineFile: na
  AuxSvNoiseBaselineFile: na
  AuxCnvPopBAlleleVcfFile: na
  AuxGermlineTaggingFile: na
  AuxCnvPanelOfNormalsFile: na

DataFields:
  - Sample_ID
  - ReferenceGenomeDir
  - VariantCallingMode
  - AuxNoiseBaselineFile
  - AuxSvNoiseBaselineFile
  - AuxCnvPopBAlleleVcfFile
  - AuxGermlineTaggingFile
  - AuxCnvPanelOfNormalsFile