---
TestType: WGS
TestName: WGS
Description: Whole Genome Sequencing
Version: 1.0.0

ApplicationProfiles:
  - ApplicationProfileName: BCLConvertNextera
    ApplicationProfileVersion: "~=1.0.0"

  - ApplicationProfileName: DragenGermlineIdtWgs
    ApplicationProfileVersion: "~=1.0.0"

